### ISSUE TITLE
Name ideas (ChatGPT)

### ISSUE THREAD

**Issue by eric-unc** [COMP523TeamD/NeuroRuler#50]
![image](https://user-images.githubusercontent.com/54514192/231495679-020671f4-c80a-45e8-934f-5a331e18d0c1.png)

Even more:
![image](https://user-images.githubusercontent.com/54514192/231495916-b8baf192-e04c-4376-9d7d-5c9cc4bf81da.png)

**Comment by jesse-wei** [comment]
Neuroruler

**Comment by jesse-wei** [comment]
# Our other ideas

CranialFit
SkullScan
CephaloData
Capomo
Heado
NogginMetrics
**CircumTool**
**Cirq**
**SizeHead**
HeadSpan
CapCalc
SizeProbe
Cerebrosizer
CranialSizer
BrainFit
Ceretica
CrownFit
NeuroSize
**NeuroRuler**
**HeadRope**
**BrainBelt**
Cranialyze(r)
Skullytics
Headfit
BrainCirc 
HeadCirc
