### ISSUE TITLE
Better data management.

### ISSUE THREAD

**Issue by eric-unc** [COMP523TeamD/NeuroRuler#61]
![image](https://user-images.githubusercontent.com/54514192/234318468-bb63a735-cc7a-483c-b95a-deb26035e13e.png)
![image](https://user-images.githubusercontent.com/54514192/234318607-20f02d11-2c4e-4937-ba04-c34b18f67f7e.png)
nani?? Why do I have to do all this stuff for my test to work locally? Why isn't this automated? @jesse-wei fix ittt plzzzzz

**Comment by eric-unc** [comment]
I think it would better to just have all the data we need in the repo, even if this makes the repo quite big.

**Comment by eric-unc** [comment]
I also don't trust dropbox to permanently hold this data (speaking from personal experience)

**Comment by mlouielu** [comment]
A way to tackle this is to cache a layer in CI so we don't need to download them each time.
